# Generated by Django 2.1.11 on 2021-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blogging', '0002_category'), ('blogging', '0003_auto_20210310_0133')]

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
